swagger: "2.0"
info:
  version: 1.0.0
  title: Staff-Management
  description: Staff-attendance-activity
basePath: /api/v1
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          
  /organisation/addOrganisation:
    post:
      tags:
        - Organisation
      summary: add organisation
      description: >-
        add new organisation
      responses:
        "201":
      parameters:
        - required: true
          name: organisationName
          in: formData
          type: string
      produces:
        - application/json
      consumes:
        - multipart/form-data
  /organisation/allOrganisations:
    get:
      tags:
        - Organisation
      summary: add organisation
      description: >-
        add new organisation
      responses:
        "200":
      produces:
        - application/json

  /admin/addAdmin:
    post:
      tags:
        - Admin
      summary: add admin
      description: >-
        add new admin
      responses:
        "201":
      parameters:
        - required: true
          name: firstName
          in: formData
          type: string
        - required: true
          name: lastName
          in: formData
          type: string
        - required: true
          name: designation
          in: formData
          type: string
        - required: true
          name: organisationId
          in: formData
          type: string
        - required: true
          name: email
          in: formData
          type: string
        - required: true
          name: mobile
          in: formData
          type: string
        - required: true
          name: password
          in: formData
          type: string
      produces:
        - application/json
      consumes:
        - multipart/form-data

  /auth/userSignin:
    post:
      tags:
        - Authorization
      summary: Returns Authorization Token
      description: >-
        Authorizes default users with username and password set as root to use
        the endpoints
      responses:
        "200":
          description: Authorization token
          examples:
            application/json:
              data: token
          schema:
            type: object
      parameters:
        - required: false
          name: email
          in: formData
          type: string
        - required: false
          name: mobile
          in: formData
          type: string
        - required: true
          name: password
          in: formData
          type: string
      produces:
        - application/json
      consumes:
        - multipart/form-data
  /auth/signup:
    post:
      tags:
        - Authorization
      summary: Register user data
      description: >-
        Register
      responses:
        "201":
          description: Registerd successfully
          examples:
            application/json:
              data: data
          schema:
            type: object
      parameters:
        - required: true
          name: firstName
          in: formData
          type: string
        - required: true
          name: lastName
          in: formData
          type: string
        - required: true
          name: email
          in: formData
          type: string
        - required: true
          name: password
          in: formData
          type: string
      produces:
        - application/json
      consumes:
        - multipart/form-data

  /employee/addEmployee:
    post:
      tags:
        - Employee
      summary: add employee
      security:
        - basicAuth: []
        - bearerAuth: []
      description: >-
        add new employee
      responses:
        "201":
      parameters:
        - required: true
          name: firstName
          in: formData
          type: string
        - required: true
          name: lastName
          in: formData
          type: string
        - required: true
          name: designation
          in: formData
          type: string
        - required: true
          name: organisationId
          in: formData
          type: string
        - required: true
          name: email
          in: formData
          type: string
        - required: true
          name: mobile
          in: formData
          type: string
      produces:
        - application/json
      consumes:
        - multipart/form-data

  /attendence/punchIn/{userId}:
    patch:
      summary: mark attendence
      tags:
        - Attendence
      parameters:
        - in: path
          name: userId
          type: string
          required: true
          description: The id to mark attendence
        - in: formData
          name: image
          type: file
          required: false
          description: Images to be uploaded
      responses:
        "200":
          description: OK
      consumes:
       - multipart/form-data
securityDefinitions:
  basicAuth:
    type: basic
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header